### PR TITLE
Update _Console_Attach.au3

### PR DESCRIPTION
**Pull request by mlipok**
support for:

and #include <Console.au3>
should be: #include '..\Console.au3'

### CODE REVIEW

**Comment by MattDiesel** [comment]
Hi @mlipok, thanks for the pull request. If this pull request and the other are just formatting/style then I'll be happy to merge without checking it, otherwise it could be a couple of weeks before I get the chance to look (I'm still busy with work despite the disruption).

Could you just quickly list any changes that might impact the behaviour of the UDF, if there are any?

**Comment by mlipok** [comment]
no one change will impact
this is only example which I clean UP 
create/enclose example in function 
```
Func _Example()
...
EndFunc
```
Added scope declaration
and fixed issue with
`#include <Console.au3>`
which should be :
`#include '..\Console.au3'`

**Comment by mlipok** [comment]
Just wait till I end edit all examples.

**Comment by MattDiesel** [comment]
Ok @mlipok , I will merge all your pull requests in order. Thanks again for your work on the project.

**Pull request merged**
